# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Federico Terzi
subtitle: Engineering Student and Developer
email: federicoterzi96@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Engineering Student and Developer based in Italy. Learn more about me and my projects,
  including Machine Learning, Mobile Apps, Web, Games and a bit of Arduino.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://federicoterzi.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  federico-terzi

permalink: /blog/:title:output_ext

collections:
  portfolios:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

social:
  name: Federico Terzi
  links:
    - https://www.youtube.com/channel/UCLXAviTgz5MuJrR_rbLGNWg
    - https://www.linkedin.com/in/federico-terzi/
    - https://github.com/federico-terzi

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
